### PR TITLE
Fix various compiler warnings

### LINKED ISSUE #23: 4.1.0: compile time warnings
First just summary stats:
```console
[tkloczko@devel-g2v SPECS]$ rpmbuild -ba ogdi.spec --quiet 2>&1 | grep -- \\[-W | sed 's/.*\[//; s/\]//' | sort | uniq -c | sort -nr
      9 -Wincompatible-pointer-types
      8 -Waddress
      3 -Wmisleading-indentation
      1 -Wimplicit-function-declaration
      1 -Wdangling-pointer=
      1 -Wbuiltin-declaration-mismatch
```
And extracted warnings from stderr
```console
../vpfrelat.c:611:13: warning: this 'for' clause does not guard... [-Wmisleading-indentation]
  611 |             for (i=start;i<end;i++)
      |             ^~~
../vpfrelat.c:614:16: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'for'
  614 |                set_nuke(&idxset);
      |                ^~~~~~~~
mkdir OBJ.Linux
../client.c: In function 'cln_PointValid':
../client.c:1784:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
 1784 |   if (oy<0)
      |   ^~
../client.c:1787:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
 1787 |     if (((dx/ox) > COMPARETOLERANCE) || ((dy/oy) > COMPARETOLERANCE)) {
      |     ^~
../object.c: In function '_closeLayerTable':
../object.c:1872:36: warning: the comparison will always evaluate as 'true' for the address of 'faceTable' will never be NULL [-Waddress]
 1872 |     if (&(lpriv->l.area.faceTable) != NULL)
      |                                    ^~
In file included from ../object.c:92:
../vrf.h:138:18: note: 'faceTable' declared here
  138 |   vpf_table_type faceTable;
      |                  ^~~~~~~~~
../object.c:1874:35: warning: the comparison will always evaluate as 'true' for the address of 'mbrTable' will never be NULL [-Waddress]
 1874 |     if (&(lpriv->l.area.mbrTable) != NULL)
      |                                   ^~
../vrf.h:139:18: note: 'mbrTable' declared here
  139 |   vpf_table_type mbrTable;
      |                  ^~~~~~~~
../object.c:1876:36: warning: the comparison will always evaluate as 'true' for the address of 'ringTable' will never be NULL [-Waddress]
 1876 |     if (&(lpriv->l.area.ringTable) != NULL)
      |                                    ^~
../vrf.h:140:18: note: 'ringTable' declared here
  140 |   vpf_table_type ringTable;
      |                  ^~~~~~~~~
../object.c:1878:36: warning: the comparison will always evaluate as 'true' for the address of 'edgeTable' will never be NULL [-Waddress]
 1878 |     if (&(lpriv->l.area.edgeTable) != NULL)
      |                                    ^~
../vrf.h:141:18: note: 'edgeTable' declared here
  141 |   vpf_table_type edgeTable;
      |                  ^~~~~~~~~
../object.c:1887:36: warning: the comparison will always evaluate as 'true' for the address of 'edgeTable' will never be NULL [-Waddress]
 1887 |     if (&(lpriv->l.line.edgeTable) != NULL)
      |                                    ^~
../vrf.h:127:18: note: 'edgeTable' declared here
  127 |   vpf_table_type edgeTable;
      |                  ^~~~~~~~~
../object.c:1889:35: warning: the comparison will always evaluate as 'true' for the address of 'mbrTable' will never be NULL [-Waddress]
 1889 |     if (&(lpriv->l.line.mbrTable) != NULL)
      |                                   ^~
../vrf.h:128:18: note: 'mbrTable' declared here
  128 |   vpf_table_type mbrTable;
      |                  ^~~~~~~~
../object.c:1896:37: warning: the comparison will always evaluate as 'true' for the address of 'primTable' will never be NULL [-Waddress]
 1896 |     if (&(lpriv->l.point.primTable) != NULL)
      |                                     ^~
../vrf.h:151:18: note: 'primTable' declared here
  151 |   vpf_table_type primTable;
      |                  ^~~~~~~~~
../object.c:1903:36: warning: the comparison will always evaluate as 'true' for the address of 'textTable' will never be NULL [-Waddress]
 1903 |     if (&(lpriv->l.text.textTable) != NULL)
      |                                    ^~
../vrf.h:161:18: note: 'textTable' declared here
  161 |   vpf_table_type textTable;
      |                  ^~~~~~~~~
../asyncsvr.c: In function 'dispatchno_1':
../asyncsvr.c:457:5: warning: this 'while' clause does not guard... [-Wmisleading-indentation]
  457 |     while (waitpid(-1, NULL, WNOHANG) > 0);
      |     ^~~~~
In file included from ../asyncsvr.c:53:
/home/tkloczko/rpmbuild/BUILD/ogdi-ogdi_4_1_0/include/Linux/ogdi_macro.h:42:25: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'while'
   42 | #define ogdi_system(fp) { \
      |                         ^
../asyncsvr.c:458:5: note: in expansion of macro 'ogdi_system'
  458 |     ogdi_system(temp);
      |     ^~~~~~~~~~~
../gdalbridge.c: In function 'GDALBridgeInitialize':
../gdalbridge.c:127:13: warning: implicit declaration of function 'strcpy' [-Wimplicit-function-declaration]
  127 |             strcpy( szPath, papszSOFilenames[iSOFile] );
      |             ^~~~~~
../gdalbridge.c:74:1: note: include '<string.h>' or provide a declaration of 'strcpy'
   73 | #include <stdlib.h>
  +++ |+#include <string.h>
   74 |
../gdalbridge.c:127:13: warning: incompatible implicit declaration of built-in function 'strcpy' [-Wbuiltin-declaration-mismatch]
  127 |             strcpy( szPath, papszSOFilenames[iSOFile] );
      |             ^~~~~~
../gdalbridge.c:127:13: note: include '<string.h>' or provide a declaration of 'strcpy'
../odbc.c: In function 'dyn_InitializeDBLink':
../odbc.c:237:39: warning: passing argument 7 of 'SQLColAttributes' from incompatible pointer type [-Wincompatible-pointer-types]
  237 |                    buffer,255,&length,(SQLINTEGER *)&(apriv->nb_field));
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                       |
      |                                       SQLINTEGER * {aka int *}
In file included from ../odbc.h:32,
                 from ../odbc.c:27:
/usr/include/sqlext.h:1922:32: note: expected 'SQLLEN *' {aka 'long int *'} but argument is of type 'SQLINTEGER *' {aka 'int *'}
 1922 |     SQLLEN                    *pfDesc);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
../odbc.c: In function 'dyn_GetColumnsInfo':
../odbc.c:397:38: warning: passing argument 7 of 'SQLColAttributes' from incompatible pointer type [-Wincompatible-pointer-types]
  397 |                      name,32,&length,&count);
      |                                      ^~~~~~
      |                                      |
      |                                      SDWORD * {aka int *}
/usr/include/sqlext.h:1922:32: note: expected 'SQLLEN *' {aka 'long int *'} but argument is of type 'SDWORD *' {aka 'int *'}
 1922 |     SQLLEN                    *pfDesc);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
../odbc.c:399:41: warning: passing argument 7 of 'SQLColAttributes' from incompatible pointer type [-Wincompatible-pointer-types]
  399 |                      buffer,513,&length,(SQLINTEGER *)&(type));
      |                                         ^~~~~~~~~~~~~~~~~~~~~
      |                                         |
      |                                         SQLINTEGER * {aka int *}
/usr/include/sqlext.h:1922:32: note: expected 'SQLLEN *' {aka 'long int *'} but argument is of type 'SQLINTEGER *' {aka 'int *'}
 1922 |     SQLLEN                    *pfDesc);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
../odbc.c:401:41: warning: passing argument 7 of 'SQLColAttributes' from incompatible pointer type [-Wincompatible-pointer-types]
  401 |                      buffer,513,&length,(SQLINTEGER *)&(readlength));
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                         |
      |                                         SQLINTEGER * {aka int *}
/usr/include/sqlext.h:1922:32: note: expected 'SQLLEN *' {aka 'long int *'} but argument is of type 'SQLINTEGER *' {aka 'int *'}
 1922 |     SQLLEN                    *pfDesc);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
../odbc.c:403:41: warning: passing argument 7 of 'SQLColAttributes' from incompatible pointer type [-Wincompatible-pointer-types]
  403 |                      buffer,513,&length,(SQLINTEGER *)&(precision));
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                         |
      |                                         SQLINTEGER * {aka int *}
/usr/include/sqlext.h:1922:32: note: expected 'SQLLEN *' {aka 'long int *'} but argument is of type 'SQLINTEGER *' {aka 'int *'}
 1922 |     SQLLEN                    *pfDesc);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
../odbc.c:405:41: warning: passing argument 7 of 'SQLColAttributes' from incompatible pointer type [-Wincompatible-pointer-types]
  405 |                      buffer,513,&length,(SQLINTEGER *)&(nullable));
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                                         |
      |                                         SQLINTEGER * {aka int *}
/usr/include/sqlext.h:1922:32: note: expected 'SQLLEN *' {aka 'long int *'} but argument is of type 'SQLINTEGER *' {aka 'int *'}
 1922 |     SQLLEN                    *pfDesc);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
../odbc.c: In function 'dyn_SelectAttributes':
../odbc.c:528:63: warning: passing argument 10 of 'SQLBindParameter' from incompatible pointer type [-Wincompatible-pointer-types]
  528 |                          (SQLPOINTER) theKey, (SQLINTEGER) 0, (SQLINTEGER *) &length) != SQL_SUCCESS) {
      |                                                               ^~~~~~~~~~~~~~~~~~~~~~
      |                                                               |
      |                                                               SQLINTEGER * {aka int *}
/usr/include/sqlext.h:2049:32: note: expected 'SQLLEN *' {aka 'long int *'} but argument is of type 'SQLINTEGER *' {aka 'int *'}
 2049 |     SQLLEN                    *pcbValue);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
../odbc.c:580:32: warning: passing argument 6 of 'SQLGetData' from incompatible pointer type [-Wincompatible-pointer-types]
  580 |                  buffer2, 255, &length);
      |                                ^~~~~~~
      |                                |
      |                                SDWORD * {aka int *}
In file included from ../odbc.h:31:
/usr/include/sql.h:706:43: note: expected 'SQLLEN *' {aka 'long int *'} but argument is of type 'SDWORD *' {aka 'int *'}
  706 |                                   SQLLEN *StrLen_or_Ind);
      |                                   ~~~~~~~~^~~~~~~~~~~~~
../odbc.c:582:45: warning: passing argument 7 of 'SQLColAttributes' from incompatible pointer type [-Wincompatible-pointer-types]
  582 |                        buffer,32,&collength,(SQLINTEGER *)&(type));
      |                                             ^~~~~~~~~~~~~~~~~~~~~
      |                                             |
      |                                             SQLINTEGER * {aka int *}
/usr/include/sqlext.h:1922:32: note: expected 'SQLLEN *' {aka 'long int *'} but argument is of type 'SQLINTEGER *' {aka 'int *'}
 1922 |     SQLLEN                    *pfDesc);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
../odbc.c:532:14: warning: storing the address of local variable 'sqlmessage' in '*error_83(D)' [-Wdangling-pointer=]
  532 |       *error = (char *)sqlmessage;
      |       ~~~~~~~^~~~~~~~~~~~~~~~~~~~
../odbc.c:515:17: note: 'sqlmessage' declared here
  515 |   unsigned char sqlmessage[SQL_MAX_MESSAGE_LENGTH];
      |                 ^~~~~~~~~~
../odbc.c:515:17: note: 'error_83(D)' declared here
```

### PR DESCRIPTION
**Pull request by rouault**
and remove ogdi/attr_driver subdirectory (ODBC stuff) (fixes #23)

### CODE REVIEW

**Comment by sharkcz** [comment]
LGTM

for the record, there are still few string op related warnings, please see build.log eg. from https://koji.fedoraproject.org/koji/taskinfo?taskID=112721420

**Comment by rouault** [comment]
@sharkcz I've added 2 extra commits that should address them

**Comment by rouault** [comment]
> thanks, all warnings are now gone except

That could be a false positive. Anyway using snprintf() like I did is safe from a security point of view. The worse that can happen is truncation, but the output table.name will be nul-terminated

**Comment by sharkcz** [comment]
OK, no objections then :-)

**Pull request merged**
