### PR TITLE
 Fall back to libtirpc if libc does not provide rpc/rpc.h 

### PR DESCRIPTION
**Pull request by devurandom**
This PR depends on: #2, #3 (please review and merge them, before merging this PR)

### CODE REVIEW

**Comment by rouault** [comment]
Do you mind rebasing on top of current master to solve the conflict ?

**Comment by praiskup** [comment]
@rouault I'd be interested to do the rebase in new PR.  But I read:

   `Experimental (one-time) convertion from CVS`

.. in project description.  Is this still experimental?

**Comment by praiskup** [comment]
Ah, there's #6  already.

**Comment by rouault** [comment]
Should be addressed by PR #6 now merged

**Pull request closed without merging**
